version: "3.9"
services:
  
  research:
    build: 
     context: .
     dockerfile: Dockerfile

    volumes:
      - ../:/home/work

    env_file:
      - env

#    user: 1000:1000

    restart: always
    container_name: Research
    runtime: nvidia

    command: poetry run jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir='/home/work'
    #command: sleep 400000

    




